language: scala

env:
  global:
    - PUBLISH_JDK=openjdk6
    # PGP_PASSPHRASE
    - secure: "XLe/gZXrGwJlKCgAUoEUIHwoh8js0IdlIazwUd5KKssZMQkPg4VfC5LLPl8iXCYIRe2JrgmD56b7eseiZF9kMxa1Rsz8fSMY0v3A0qwxRjbsxVQ2NqEvdq+TNOAhjo/OmPnipvTcDdAyq68Ca4nTSBtfBpy5t6X3Z4UIl8CWLdw="
    # SONA_USER
    - secure: "Me+3gxk89qOq18J+N/N+VoxnG8bSTrgyGovutLRFQnSNkJQXoVawJul9BmCZVrha7y/WCwsbSFFP9vS3VnKjPne5RnQM4eNjPOUw08uBtoj6QD/jpmRjt+cEWMaD9tB9OvJLkaKRFyTy8Un2tVO4ia9GEdojy2YbqjrJjGqwW9E="
    # SONA_PASS
    - secure: "cjzluj1FGCr2D/3TgnV/7yOELOcqB8QG6Du95tb4xPp39+ulrIfTvzQ8HA1oC8+y1mmN68h5RxN/gcC+9GdihDpk+bXz2Ij7XWmp+tiHU8E6VNS+rd+JO7Ojf90q6jsmx00Y8uhZ/RZtjK+p8SUTC0a5KhqesmxSThHFqPNC5CM="

script: admin/build.sh

jdk:
  - openjdk6
  - openjdk7

notifications:
  email: adriaan.moors@typesafe.com
